export declare type Size =
  | 'mini'
  | 'tiny'
  | 'small'
  | 'medium'
  | 'large'
  | 'big'
  | 'huge'
  | 'massive'
export declare type Wide =
  | 'two'
  | 'three'
  | 'four'
  | 'five'
  | 'six'
  | 'seven'
  | 'eight'
  | 'nine'
  | 'ten'
  | 'eleven'
  | 'twelve'
  | 'thirteen'
  | 'fourteen'
  | 'fifteen'
  | 'sixteen'
export declare type State = 'disabled' | 'loading'
export declare type Rotate = 'counterclockwise' | 'clockwise'
export declare type Flip = 'horizontally' | 'vertically'
export declare type Color =
  | 'primary'
  | 'secondary'
  | 'positive'
  | 'negative'
  | 'red'
  | 'orange'
  | 'yellow'
  | 'olive'
  | 'teal'
  | 'green'
  | 'blue'
  | 'violet'
  | 'purple'
  | 'pink'
  | 'brown'
  | 'grey'
  | 'black'
export declare type Attach = boolean | 'left' | 'right' | 'top' | 'bottom'
export declare type Float = 'left' | 'right'
export declare type Align = 'left' | 'center' | 'right'
export declare type VAlign = 'top' | 'middle' | 'bottom'
export declare type Speed = 'slow' | 'fast'
export declare type Loading = 'elastic' | 'double'
